"""empty message

Revision ID: f1cfdec0bbbf
Revises: 
Create Date: 2020-07-24 08:17:45.568601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cfdec0bbbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_email_signup_timestamp'), 'email_signup', ['timestamp'], unique=False)
    op.create_index(op.f('ix_email_signup_updated'), 'email_signup', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_signup_updated'), table_name='email_signup')
    op.drop_index(op.f('ix_email_signup_timestamp'), table_name='email_signup')
    op.drop_table('email_signup')
    # ### end Alembic commands ###
